name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Verify fonts directory
      - name: Check fonts directory
        run: |
          echo "Checking fonts directory structure..."
          ls -R public/assets/fonts/

      - name: Build project
        run: yarn build
        env:
          CI: true

      - name: Check build output
        run: |
          echo "Checking build output..."
          ls -R docs/

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./docs 
          retention-days: 14

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./docs 

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # Changed from ./dist to ./docs
          cname: ${{ secrets.CNAME || '' }}
          enable_jekyll: false
          force_orphan: true