name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Show environment info
        run: |
          node --version
          yarn --version
          pwd
          ls -la

      - name: Check file structure
        run: |
          echo "Checking file structure..."
          ls -R src/components/
          echo "Checking TechStackChip.tsx exists..."
          cat src/components/atoms/TechStackChip.tsx

      - name: Remove package-lock.json
        run: rm -f package-lock.json

      - name: Clean install
        run: |
          rm -rf node_modules
          rm -rf ~/.cache/yarn
          yarn cache clean
          yarn install --frozen-lockfile

      - name: Type check
        run: yarn tsc --noEmit

      - name: Build project
        run: yarn build
        env:
          CI: true

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist
          retention-days: 1

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist